#filters:
#  ip:
#    ignores: 118.190.146.220,118.190.144.11
#  path:
#    ignores: /mall/goods/details,/sm/config,/sm/registry,/eureka,/sm/admin,/zipkin,/wx/index,/wx/auth/code,/app/message/notice/detail,/app/proxy,/app/callback,/mgt/proxy,/mgt/callback,/job/callback,/data,/upms/mgt/pwd,/upms/mgt/msgCode,/upms/legality,/upms/sign,/js/,/css/,/app/v1/paypasswd/resetPage/proxy/
zuul:
  host:
    connect-timeout-millis: 6000
    socet-timeout-millis: 6000
  sensitive-headers:
  ignoredHeaders: x-application-context
  routes:
    provider-one: /api/provider/one/**
    consumer-one: /api/consumer/one/**
    # 服务管理配置
#    p2p-sm-registry:
#      path: /sm/registry/**
#      serviceId: p2p-sm-registry

  add-host-header: true
  AccessFilter:
    pre:
      disable: false

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
feign:
  hystrix:
    enabled: true
