#spring:
#  application:
#    name: springcloud-registry
#    port: 10000

server:
  port: 10000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  security:
    enable: false